### ISSUE TITLE
#Req Features

### ISSUE THREAD

**Issue by MaxxRider** [azamaulanaaa/botkaca#18] opened 2020-10-15 07:34 UTC
👲If possible add These Feature 👇

1= Custome File Name support
2= Thumbnail save via Command instead of Caption
3= Unzip ,unrar ,zip, untar
4=Fix thumbnail issue in upload as Doc

**Comment by azamaulanaaa** [comment] 2020-10-15 16:24
Duplicate of #8 #14 #15  #12

**Closed as completed by azamaulanaaa** 2020-10-15 16:24 UTC

**Comment by azamaulanaaa** [comment] 2020-10-15 16:34
oh sorry, I missed no 2. Thumbnail save via caption I think the best way to do it because it has less complexity and change thumbnail in one action.

**Comment by MaxxRider** [comment] 2020-10-16 06:43
ok atleast Add  Custome File Name support 🙈
custome File Name is important thing I think
